function TLangEng() {
	/* This is a main english text file */
	
	this.texts = {
		"Greetings" 			: "Hello. This is a little game designed to help getting to know yourself and each other.",
		"InstructionsQuestion"  : "Do you need instructions?",
		"Instructions"  		: "Ok! First, you are going to choose who is going to play. Next, you'll be presented with choices, one at a time, where the player can choose one of the choices avaluble, both of them, none of them, something else entirely, or decide to skip or discard the question altogether. It's ok either way. A textfield to leave a optional comment is also available. There are no rules on what basis the player can choose - any kind of a personal preference or assosiation is valid. Once you click on any button exept the comment option, another choice will pop up and so on. Do you want to read the FAQ?",
		"FAQ"					: "FAQ is under construction. Ask the developer questions to fill this void!",
		"ChoosePlayer"			: "Who is going to play? (you can enter multiple players by seperating names with commas)",
		"Welcome"				: "Welcome",
		"DoYouPrefer"			: "Do you prefer",
		"OptionBoth"			: "Both",
		"OptionNeither"			: "Neither",
		"OptionOther"			: "Other",
		"OptionComment"			: "Comment",
		"OptionSkip"			: "Skip",
		"OptionDiscard"			: "Discard",
		"Or"					: "or",
		"Yes"					: "Yes",
		"No"					: "No",
		"SaveToFile"			: "Save to file",
		"LoadFromFile"			: "Load from file",
		"SavedAlert"			: 'A log file was saved as "TulDevelopGameSave.txt" in your default download folder',
		"Submit"				: "Submit",
		"ChangePlayerName"		: "Change",
		"AddPlayer"				: "Add player",
		"RemovePlayer"			: "Remove",
	}
	
	this.questions = [
		["Coffee", "Tea"],
		["Clear Sky","Rain"],
		["Will", "Wits"],
		["Mess", "Cleanness"],
		["Power", "Freedom"],
		["Milk", "Sugar"],
		["War", "Peace"],
		["Combat", "Trade"],
		["to Command", "to Lead"],
		["Tactics", "Strategy"],
		["to Attack", "to Defend"],
		["a Hammer", "a Bow"],
		["Speed", "Strength"],
		["Art", "Work"],
		["the Sky", "the Sea"],
		["an Adventure", "Love"],
		["a Book", "a Door"],
		["Dogs", "Cats"],
		["Stealth", "Diplomacy"],
		["the Earth", "Space"],
		["the Stars", "the Void"],
		["Connections", "Knowledge"],
		["an Enemy", "Uncertainty"],
		["to play Chess", "to Race"],
		["a Sword", "a Shield"],
		["a Pet", "a Car"],
		["being Secure", "being Loved"],
		["Fire", "Water"],
		["a Forest", "a Road"],
		["a City", "Wildness"],
		["Magic", "Technology"],
		["Duty", "Friendship"],
		["Lasers", "Emotions"],
		["Truth", "Dare"],
		["to Hide", "to Seek"],
		["to Contact", "to Protect"],
		["Money", "Health"],
		["the Past", "the Future"],
		["to Listen", "to Act"],
		["Robots", "Humans"],
		["to Support", "to Engage"],
		["Crystals", "Trees"],
		["to Destroy", "to Build"],
		["a Story", "a Song"],
		["Sports", "Art"],
		["Math", "Philosophy"],
		["to Read", "to Write"],
		["Unity", "Diversity"],
		["a Gun", "a Pen"],
		["Death", "Dishonour"],
		["to Fight", "to Run away"],
		["Nature", "Architecture"],
		["Pizza", "Sushi"],
		["Rare Steak", "Green Salad"],
		["Texting", "Talking"],
		["Dinosaurs", "Dragons"],
		["a Wolf", "a Ferret"],
		["a Seagull", "a Lion"],
		["an Encyclopedia", "a Multitool"],
		["Batman", "Spiderman"],
		["Movies", "Computer Games"],
		["Charm", "Luck"],
		["Programming", "Cooking"],
		["to Cheat", "to Retry"],
		["Tacos", "Cake"],
		["Beer", "Spring Water"],
		["Wine", "Vodka"],
		["Day", "Night"],
		["to be a Mechanic", "to be a Pilot"],
		["a Plane", "a Tank"],
		["Quiet", "Music"],
		["Classical Music", "Heavy Metal"],
		["Snakes", "Sharks"],
		["Ice cream", "Pringles"],
	]
}