function TLangEng() {
	/* This is a main english text file */
	
	this.texts = {
		"Greetings" 			: "Hello. This is a little game designed to help getting to know yourself and each other.",
		"InstructionsQuestion"  : "Do you need instructions?",
		"Instructions"  		: 'This is a small dialogue game. For every stage, you will be presented a choice (for example "Coffee or Tea?") and asked to choose one of them. You can also choose "Other" and write anything you like there. Once the choice is made, a next question will pop up until there are no more questions in the bank. <br> You may play this game for yourself for fun or as a introspection practice but if you are developing characters, for example you are a writer, an actor, a game designer or a gamemaster in an RPG - you can enter the name of your character and then choose the choices that would suit him or her. <br> It is also possible to play with multiple characters at the same time to get a feeling of their differences and commonalities for every questions. <br> At any point of the game, you can export the current log into a text file and get a neat character information sheet that can be shared, modified, or loaded back into the game to continue for that point. Have fun!',		"FAQ"					: "FAQ is under construction. Ask the developer questions to fill this void!",
		"ChoosePlayer"			: "Who is going to play? (you can enter multiple players by seperating names with commas)",
		"Welcome"				: "Welcome",
		"DoYouPrefer"			: "Do you prefer",
		"OptionBoth"			: "Both",
		"OptionNeither"			: "Neither",
		"OptionOther"			: "Other",
		"OptionComment"			: "Comment",
		"OptionSkip"			: "Skip",
		"OptionDiscard"			: "Discard",
		"Or"					: "or",
		"Yes"					: "Yes",
		"No"					: "No",
		"SaveToFile"			: "Save to file",
		"LoadFromFile"			: "Load from file",
		"SavedAlert"			: 'A log file was saved as "GameOfChoices.txt" in your default download folder',
		"Submit"				: "Submit",
		"ChangePlayerName"		: "Change",
		"AddPlayer"				: "Add player",
		"RemovePlayer"			: "Remove",
	}
	
	this.questions = [
		["Coffee", "Tea"],
		["Clear Sky","Rain"],
		["Will", "Wits"],
		["Mess", "Cleanness"],
		["Power", "Freedom"],
		["Milk", "Sugar"],
		["War", "Peace"],
		["Combat", "Trade"],
		["to Command", "to Lead"],
		["Tactics", "Strategy"],
		["to Attack", "to Defend"],
		["a Hammer", "a Bow"],
		["Speed", "Strength"],
		["Art", "Work"],
		["the Sky", "the Sea"],
		["an Adventure", "Love"],
		["a Book", "a Door"],
		["Dogs", "Cats"],
		["Stealth", "Diplomacy"],
		["the Earth", "Space"],
		["the Stars", "the Void"],
		["Connections", "Knowledge"],
		["an Enemy", "Uncertainty"],
		["to play Chess", "to Race"],
		["a Sword", "a Shield"],
		["a Pet", "a Car"],
		["being Secure", "being Loved"],
		["Fire", "Water"],
		["a Forest", "a Road"],
		["a City", "Wildness"],
		["Magic", "Technology"],
		["Duty", "Friendship"],
		["Lasers", "Emotions"],
		["Truth", "Dare"],
		["to Hide", "to Seek"],
		["to Contact", "to Protect"],
		["Money", "Health"],
		["the Past", "the Future"],
		["to Listen", "to Act"],
		["Robots", "Humans"],
		["to Support", "to Engage"],
		["Crystals", "Trees"],
		["to Destroy", "to Build"],
		["a Story", "a Song"],
		["Sports", "Art"],
		["Math", "Philosophy"],
		["to Read", "to Write"],
		["Unity", "Diversity"],
		["a Gun", "a Pen"],
		["Death", "Dishonour"],
		["to Fight", "to Run away"],
		["Nature", "Architecture"],
		["Pizza", "Sushi"],
		["Rare Steak", "Green Salad"],
		["Texting", "Talking"],
		["Dinosaurs", "Dragons"],
		["a Wolf", "a Ferret"],
		["a Seagull", "a Lion"],
		["an Encyclopedia", "a Multitool"],
		["Batman", "Spiderman"],
		["Movies", "Computer Games"],
		["Charm", "Luck"],
		["Programming", "Cooking"],
		["to Cheat", "to Retry"],
		["Tacos", "Cake"],
		["Beer", "Spring Water"],
		["Wine", "Vodka"],
		["Day", "Night"],
		["to be a Mechanic", "to be a Pilot"],
		["a Plane", "a Tank"],
		["Quiet", "Music"],
		["Classical Music", "Heavy Metal"],
		["Snakes", "Sharks"],
		["Ice cream", "Pringles"],
	]
}
